# Generated by Django 4.2.5 on 2023-10-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_recipes_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='time',
            field=models.IntegerField(choices=[], null=True),
        ),
    ]
