# Generated by Django 4.2.5 on 2023-10-04 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_recipes_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='time',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(0)]),
        ),
    ]
